Desktop
Jhaman1895/Personal-Portfolio-2 pull request #7
Opened 2022-07-16 16:25 UTC by Jhaman1895

Added the desktop version of personal portfolio to the existing mobile version.

2022-07-16 16:53 UTC, KayLemba requested changes
Hi @Jhaman1895   👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
GitHub flow is followed. ✔️

Required Changes ♻️
Check the comments under the review in the inline comments.

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-07-16 16:53 UTC, KayLemba commented on index.html
> +          </div>
While you did a nice job working on the project requirements. There are still some issues you need to correct. The content of this part of the page seems to be overlaping. Please correct this and carefully inspect the figma template. 

This is your design:
![Screenshot from 2022-07-16 20-38-59](https://user-images.githubusercontent.com/79506105/179364363-30b396b1-e2a8-40bc-b848-9c127ae737ea.png)

Follow this design:
![Screenshot from 2022-07-16 20-40-47](https://user-images.githubusercontent.com/79506105/179364417-7d161a0f-37a7-4dea-94a1-2203357eb22b.png)

2022-08-26 08:45 UTC, Jhaman1895 commented
## In this Milestone, I have taken the following steps to create the desktop version of template-2 from the given Figma design:
- [  ] Used the mobile-first responsive design principle.
-  [  ] Implemented a media query and adjusted the markup accordingly to transition from the mobile to the desktop version.
-  [  ]  Implemented CSS grid to layout the recent works section and CSS flexbox to layout the rest.

2022-08-26 10:10 UTC, KayLemba approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @Jhaman1895        , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 
- No linter errors 
- Neat and Nice User interface 


Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-30 08:27 UTC, merged